services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "loan-application-platform-backend"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DB_URL=${DB_URL}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - CACHE_URL=${CACHE_URL}
      - CACHE_PORT=${CACHE_PORT}
      - CURRENCY_API_KEY=${CURRENCY_API_KEY}
      - CURRENCY_API_BASE_URL=${CURRENCY_API_BASE_URL}
      - CURRENCY_API_EXCHANGE_URI=${CURRENCY_API_EXCHANGE_URI}
      - CURRENCY_API_EXCHANGE_CACHE_TTL=${CURRENCY_API_EXCHANGE_CACHE_TTL}
      - CURRENCY_API_CURRENCIES_URI=${CURRENCY_API_CURRENCIES_URI}
      - CURRENCY_API_CURRENCIES_TTL=${CURRENCY_API_CURRENCIES_TTL}
      - DEFUALT_EXCHANGE_CURRENCY=${DEFUALT_EXCHANGE_CURRENCY}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
      - cache
    networks:
      - backend-network
      - frontend-network

  db:
    image: mongo:7.0
    environment:
      - DB_PORT=${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/data/db
    networks:
      - backend-network

  cache:
    image: redis:7.2
    environment:
      - CACHE_PORT=${CACHE_PORT}
    ports:
      - "${CACHE_PORT}:${CACHE_PORT}"
    volumes:
      - cache-data:/data
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    expose:
      - ${FRONTEND_PORT}
    depends_on:
      - backend
    networks:
      - frontend-network

volumes:
  db-data:
  cache-data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge